<?php

namespace App\Tests\Unit\Service\WarehouseStorageBin\AutoGenerate\Iterators;

use App\DTO\WarehouseStorageBinAutoGenerateData;
use App\Service\WarehouseStorageBin\AutoGenerate\Iterators\CellIterator;
use Mockery\Adapter\Phpunit\MockeryTestCase;

class CellIteratorTest extends MockeryTestCase
{
    private ?CellIterator $cellIterator;

    private ?WarehouseStorageBinAutoGenerateData $autoGenerateData;

    public function setUp(): void
    {
        parent::setUp();

        $this->autoGenerateData = \Mockery::mock(WarehouseStorageBinAutoGenerateData::class);
    }

    public function tearDown(): void
    {
        $this->autoGenerateData = null;
        $this->cellIterator     = null;

        parent::tearDown();
    }

    public function testItIterateWithIncrement1Step(): void
    {
        $this->autoGenerateData->shouldReceive('getStartValue')
                               ->once()
                               ->withNoArgs()
                               ->andReturn('AA-A1-01');

        $this->autoGenerateData->shouldReceive('getEndValue')
                               ->once()
                               ->withNoArgs()
                               ->andReturn('AB-A2-02');
        $this->autoGenerateData->shouldReceive('getIncrement')
                               ->once()
                               ->withNoArgs()
                               ->andReturn('01-01-01');

        $this->cellIterator = new CellIterator($this->autoGenerateData);

        $expected = ['AA-A1-01', 'AA-A1-02', 'AA-A2-01', 'AA-A2-02', 'AB-A1-01', 'AB-A1-02', 'AB-A2-01', 'AB-A2-02'];

        self::assertSame($expected, $this->cellIterator->toArray());
    }

    public function testItIterateWithIncrement2StepInBaySection(): void
    {
        $this->autoGenerateData->shouldReceive('getStartValue')
                               ->once()
                               ->withNoArgs()
                               ->andReturn('AA-A1-01');

        $this->autoGenerateData->shouldReceive('getEndValue')
                               ->once()
                               ->withNoArgs()
                               ->andReturn('AB-A2-02');
        $this->autoGenerateData->shouldReceive('getIncrement')
                               ->once()
                               ->withNoArgs()
                               ->andReturn('01-02-01');

        $this->cellIterator = new CellIterator($this->autoGenerateData);

        $expected = ['AA-A1-01', 'AA-A1-02', 'AB-A1-01', 'AB-A1-02'];

        self::assertSame($expected, $this->cellIterator->toArray());
    }

    public function testItIterateWithIncrement2StepInAisleSection(): void
    {
        $this->autoGenerateData->shouldReceive('getStartValue')
                               ->once()
                               ->withNoArgs()
                               ->andReturn('AA-A1-01');

        $this->autoGenerateData->shouldReceive('getEndValue')
                               ->once()
                               ->withNoArgs()
                               ->andReturn('AB-A2-02');
        $this->autoGenerateData->shouldReceive('getIncrement')
                               ->once()
                               ->withNoArgs()
                               ->andReturn('02-01-01');

        $this->cellIterator = new CellIterator($this->autoGenerateData);

        $expected = ['AA-A1-01', 'AA-A1-02', 'AA-A2-01', 'AA-A2-02'];

        self::assertSame($expected, $this->cellIterator->toArray());
    }
}
