<?php

namespace App\Service\WarehouseStorageBin\AutoGenerate\Editors;

use App\Dictionary\StorageBinAutoGenerationStorageLevelDictionary;
use App\Dictionary\StorageBinTypeDictionary;
use App\DTO\WarehouseStorageBinAutoGenerateData;

final class BayEditor extends AbstractEditor
{
    public function supports(WarehouseStorageBinAutoGenerateData $data): bool
    {
        return $data->getStorageLevel() === StorageBinAutoGenerationStorageLevelDictionary::BAY;
    }

    protected function aggregate(WarehouseStorageBinAutoGenerateData $data): array
    {
        $bays = $this->aggregateFromDatabase($data);

        $cells = $this->mergeChildren($bays);

        return array_merge($bays, $cells);
    }

    protected function getType(): string
    {
        return StorageBinTypeDictionary::BAY;
    }
}
