<?php

namespace App\Service\WarehouseStorageBin\AutoGenerate\Editors;

use App\DTO\WarehouseStorageBinAutoGenerateData;

interface EditorInterface
{
    public function supports(WarehouseStorageBinAutoGenerateData $data): bool;

    public function edit(WarehouseStorageBinAutoGenerateData $data): array;
}
