<?php

namespace App\DTO;

use App\Entity\Warehouse;
use App\Entity\WarehouseStorageArea;

final class WarehouseStorageBinAutoGenerateData
{
    private string $actionType;

    private string $storageLevel;

    private string $startValue;

    private string $endValue;

    private string $increment;

    private Warehouse $warehouse;

    private WarehouseStorageArea $warehouseStorageArea;

    private bool $isActiveForStow;

    private bool $isActiveForPick;

    private ?int $quantityCapacity;

    private ?int $widthCapacity;

    private ?int $heightCapacity;

    private ?int $lengthCapacity;

    private ?int $weightCapacity;

    public function getActionType(): string
    {
        return $this->actionType;
    }

    public function setActionType(string $actionType): void
    {
        $this->actionType = $actionType;
    }

    public function getStorageLevel(): string
    {
        return $this->storageLevel;
    }

    public function setStorageLevel(string $storageLevel): void
    {
        $this->storageLevel = $storageLevel;
    }

    public function getStartValue(): string
    {
        return $this->startValue;
    }

    public function setStartValue(string $startValue): void
    {
        $this->startValue = $startValue;
    }

    public function getEndValue(): string
    {
        return $this->endValue;
    }

    public function setEndValue(string $endValue): void
    {
        $this->endValue = $endValue;
    }

    public function getIncrement(): string
    {
        return $this->increment;
    }

    public function setIncrement(string $increment): void
    {
        $this->increment = $increment;
    }

    public function getWarehouse(): Warehouse
    {
        return $this->warehouse;
    }

    public function setWarehouse(Warehouse $warehouse): void
    {
        $this->warehouse = $warehouse;
    }

    public function getWarehouseStorageArea(): WarehouseStorageArea
    {
        return $this->warehouseStorageArea;
    }

    public function setWarehouseStorageArea(WarehouseStorageArea $warehouseStorageArea): void
    {
        $this->warehouseStorageArea = $warehouseStorageArea;
    }

    public function getIsActiveForStow(): bool
    {
        return $this->isActiveForStow;
    }

    public function setIsActiveForStow(bool $isActiveForStow): void
    {
        $this->isActiveForStow = $isActiveForStow;
    }

    public function getIsActiveForPick(): bool
    {
        return $this->isActiveForPick;
    }

    public function setIsActiveForPick(bool $isActiveForPick): void
    {
        $this->isActiveForPick = $isActiveForPick;
    }

    public function getQuantityCapacity(): ?int
    {
        return $this->quantityCapacity;
    }

    public function setQuantityCapacity(?int $quantityCapacity): void
    {
        $this->quantityCapacity = $quantityCapacity;
    }

    public function getWidthCapacity(): ?int
    {
        return $this->widthCapacity;
    }

    public function setWidthCapacity(?int $widthCapacity): void
    {
        $this->widthCapacity = $widthCapacity;
    }

    public function getHeightCapacity(): ?int
    {
        return $this->heightCapacity;
    }

    public function setHeightCapacity(?int $heightCapacity): void
    {
        $this->heightCapacity = $heightCapacity;
    }

    public function getLengthCapacity(): ?int
    {
        return $this->lengthCapacity;
    }

    public function setLengthCapacity(?int $lengthCapacity): void
    {
        $this->lengthCapacity = $lengthCapacity;
    }

    public function getWeightCapacity(): ?int
    {
        return $this->weightCapacity;
    }

    public function setWeightCapacity(?int $weightCapacity): void
    {
        $this->weightCapacity = $weightCapacity;
    }
}
