<?php

namespace App\Service\WarehouseStorageBin\AutoGenerate;

use App\DTO\WarehouseStorageBinAutoGenerateData;
use App\Entity\WarehouseStorageBin;

final class BinDataSetter
{
    public function setData(
        WarehouseStorageBin $binObject,
        WarehouseStorageBinAutoGenerateData $data
    ): WarehouseStorageBin {
        if (!empty($data->getHeightCapacity())) {
            $binObject->setHeightCapacity($data->getHeightCapacity());
        }

        if (!empty($data->getWidthCapacity())) {
            $binObject->setWidthCapacity($data->getWidthCapacity());
        }

        if (!empty($data->getWeightCapacity())) {
            $binObject->setWeightCapacity($data->getWeightCapacity());
        }

        if (!empty($data->getLengthCapacity())) {
            $binObject->setLengthCapacity($data->getLengthCapacity());
        }

        if (!empty($data->getQuantityCapacity())) {
            $binObject->setQuantityCapacity($data->getQuantityCapacity());
        }
        $binObject->setIsActiveForPick($data->getIsActiveForPick())
                  ->setIsActiveForStow($data->getIsActiveForStow())
                  ->setWarehouse($data->getWarehouse())
                  ->setWarehouseStorageArea($data->getWarehouseStorageArea());

        return $binObject;
    }
}
