parameters:
  env(APP_LOAD_FIXTURES): true
  app.load_fixtures: '%env(bool:APP_LOAD_FIXTURES)%'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      $binTemplate: '%env(WAREHOUSE_STORAGE_BIN_TEMPLATE)%'

