<?php

namespace App\Service\WarehouseStorageBin\AutoGenerate\Handlers;

use App\Dictionary\StorageBinAutoGenerationActionTypeDictionary;
use App\DTO\WarehouseStorageBinAutoGenerateData;
use App\Service\WarehouseStorageBin\AutoGenerate\Editors\EditorInterface;

final class EditHandler implements HandlerInterface
{
    public function __construct(private iterable $editors)
    {
    }

    public function supports(WarehouseStorageBinAutoGenerateData $data): bool
    {
        return $data->getActionType() === StorageBinAutoGenerationActionTypeDictionary::EDIT;
    }

    public function handle(WarehouseStorageBinAutoGenerateData $data): array
    {
        /** @var EditorInterface $editor */
        foreach ($this->editors as $editor) {
            if ($editor->supports($data)) {
                return $editor->edit($data);
            }
        }
    }
}
