<?php

namespace App\Service\WarehouseStorageBin\AutoGenerate\Handlers;

use App\DTO\WarehouseStorageBinAutoGenerateData;

interface HandlerInterface
{
    public function supports(WarehouseStorageBinAutoGenerateData $data): bool;

    public function handle(WarehouseStorageBinAutoGenerateData $data): array;
}
