<?php

namespace App\Service\WarehouseStorageBin\AutoGenerate\Creators;

use App\Dictionary\StorageBinAutoGenerationStorageLevelDictionary;
use App\Dictionary\StorageBinTypeDictionary;
use App\DTO\WarehouseStorageBinAutoGenerateData;
use App\Entity\WarehouseStorageBin;
use App\Service\WarehouseStorageBin\Exceptions\ParentNotFoundException;

final class AisleCreator extends AbstractCreator
{
    public function supports(WarehouseStorageBinAutoGenerateData $data): bool
    {
        return in_array($data->getStorageLevel(), StorageBinAutoGenerationStorageLevelDictionary::toArray());
    }

    protected function getType(): string
    {
        return StorageBinTypeDictionary::AISLE;
    }

    protected function getFormattedParentSerial(string $formattedSerial): string
    {
        // Aisle does not have parent, So we return empty value.
        return '';
    }

    public static function getPriority(): int
    {
        return 3;
    }
}
