<?php

namespace App\Service\WarehouseStorageBin\AutoGenerate\Creators;

use App\Dictionary\StorageBinAutoGenerationStorageLevelDictionary;
use App\Dictionary\StorageBinTypeDictionary;
use App\DTO\WarehouseStorageBinAutoGenerateData;

final class BayCreator extends AbstractCreator
{
    public function supports(WarehouseStorageBinAutoGenerateData $data): bool
    {
        return in_array($data->getStorageLevel(), [
            StorageBinAutoGenerationStorageLevelDictionary::BAY,
            StorageBinAutoGenerationStorageLevelDictionary::CELL,
        ]);
    }

    public function getType(): string
    {
        return StorageBinTypeDictionary::BAY;
    }

    protected function getFormattedParentSerial(string $formattedSerial): string
    {
        // Formatted serial format is W1A1-AA-A0-00.
        // So bay's parent serial is: W1A1-AA

        $serials = explode('-', $formattedSerial);

        return $this->concatSerials($serials[0], $serials[1]);
    }

    public static function getPriority(): int
    {
        return 2;
    }
}
