<?php

namespace App\Service\WarehouseStorageBin\AutoGenerate\Creators;

use App\Dictionary\StorageBinAutoGenerationStorageLevelDictionary;
use App\Dictionary\StorageBinTypeDictionary;
use App\DTO\WarehouseStorageBinAutoGenerateData;

final class CellCreator extends AbstractCreator
{
    public function supports(WarehouseStorageBinAutoGenerateData $data): bool
    {
        return $data->getStorageLevel() === StorageBinAutoGenerationStorageLevelDictionary::CELL;
    }

    public function getType(): string
    {
        return StorageBinTypeDictionary::CELL;
    }

    protected function getFormattedParentSerial(string $formattedSerial): string
    {
        // Formatted serial format is W1A1-AA-A0-00.
        // So cell's parent serial is: W1A1-AA-A0

        $serials = explode('-', $formattedSerial);

        return $this->concatSerials($serials[0], $serials[1], $serials[2]);
    }

    public static function getPriority(): int
    {
        return 1;
    }
}
