<?php

namespace App\Service\WarehouseStorageBin\AutoGenerate\Creators;

use App\DTO\WarehouseStorageBinAutoGenerateData;

interface CreatorInterface
{
    public function supports(WarehouseStorageBinAutoGenerateData $data): bool;

    public function create(WarehouseStorageBinAutoGenerateData $data): array;

    public static function getPriority(): int;
}
